/**
 * Constants used throughout application
 */
export const constants = {
    projectFileExtension: '.ann',
    assetMetadataFileExtension: '-asset.json',
    assetMetadataListFileExtension: '-asset-list.json',
    regionMetadataListFileExtension: '-region-list.json',
    exportFileExtension: '-export.json',
    projectTargetDirectoryName: 'annotation',
    projectReportDirectoryName: 'report',
    reportFileName: 'report.json',
    databaseFileName: 'database.json',
    lockFileName: 'update.lock',
    storeJSON: 'store.json',
    freezeJSON: 'freeze.json',
    freezeStoreJSON: 'freeze_store.json',
    defaultTagsFile: 'tags.json',
    appSettingsFile: 'annotator_settings.json',
    instructionFile: 'instruction.html',
    lockFileExtention: 'lock',
    privateInfoFormSchema: 'privateInfoForm.json',
    privateInfoUiSchema: 'privateInfoForm.ui.json',
    metaInfoFormSchema: 'metaInfoForm.json',
    metaInfoUiSchema: 'metaInfoForm.ui.json',
    patientInfoFormSchema: 'patientInfoForm.json',
    patientInfoUiSchema: 'patientInfoForm.ui.json',
    lesionInfoFormSchema: 'lesionInfoForm.json',
    lesionInfoUiSchema: 'lesionInfoForm.ui.json',
    tagsFile: 'tags.json',
    exportSummaryReportFile: 'reportSummary.csv',
    exportPatientReportFile: 'reportPatient.csv',
    exportLesionsReportFile: 'reportLesions.csv',
    exportPrivateReportFile: 'reportPrivate.csv',
    logFile: 'annotator.log',
    tagColors: {
        Red: '#FF0000',
        Maroon: '#800000',
        Yellow: '#FFFF00',
        Olive: '#808000',
        Lime: '#00FF00',
        Green: '#008000',
        Aqua: '#00FFFF',
        Teal: '#008080',
        Blue: '#0000FF',
        Navy: '#000080',
        Fuschia: '#FF00FF',
        Purple: '#800080',
    },
} as const
